### ISSUE TITLE
批评邓小平改革开放-先富带动后富

### ISSUE THREAD

**Issue by singer01** [0x24a/ESPFlask#1]
<html>
<body>
<p style="font-family: Quicksand, serif; color: white; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: pre-wrap; background-color: rgb(34, 34, 34); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">这应该是上个世纪最大的政治谎言了。
“在经济政策上，我认为要允许一部分地区、一部分企业、一部分工人农民，由于辛勤努力成绩大而收入多一些，生活先好起来。一部分人生活先好起来，就必然产生极大的示范力量，影响左邻右舍，带动其他地区、其他单位的人们向他们学习。这样，就会使整个国家经济不断地波浪式向前发展，使全国各民族人民都比较快地富起来。”
——《邓小平文选》
你看看吧，工人们富不富。我只强调一下，资本家不是慈善家。
（对于上面邓小平的话，）这就是说，要使一部分人先富裕起来，就得搞资本主义。但是一旦搞资本主义，就只能是永远一小部分人发财，不可能有共同富裕了，因为那一部分人要发
财就得靠剥削他人。财富终究是有限的，而一部分人先富裕的条件又不是普遍的，所以能富裕起来的只能是一部分人。实际上，暴发户们没有一个是通过自己辛勤劳动致富的，都是发的不
义之财，至少也是合法剥削致富。由于他们发的都是不义之财，所以就会人富心变，富了还想更富，要永远保持富裕的势头，怎么会分散自己的实力去帮助穷人共同富裕呢？1998年闹大洪水时，全国人民捐款20亿元，其中只有个别富人捐款。当时，富裕阶层手中有4万亿元存款，他们只要拿出1%存款，就是400亿元，就是全国人民捐款的20倍。要富人捐款，比割他们的肉
还心疼，他们还怎么会帮助穷人致富呢？所以邓先生设计的先富带后富，只是水中月镜中花墙上画饼的幻觉而已，是中听不中用的。
——毛继东《邓小平言论自相矛盾“百花大观园”》
</p><div class="mapprofile-render-container" style="font-family: Quicksand, serif; margin: 20px 50px; padding: 15px; max-height: 100%; overflow: hidden; border: 1px solid white; background-color: black; color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="relative" style="font-family: Quicksand, serif; position: relative; top: 0px; left: 0px;">
 
--

</div></div>
</body>
</html>

**Comment by 0x24a** [comment]
你妈死了
